# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# https://copier.readthedocs.io/en/stable/configuring/#the-copier-answersyml-file
_commit: v0.0.9
_src_path: gh:FallingColors/hexdummy
author: Prismatica
capitalize_platforms: false
classname: BoundedFields
default_branch: main
description: A new way of binding your hexes to the world.
display_name: Bounded Fields
github_repo: boundedfields
hexcasting_version: 0.10.3
homepage_url: https://prismatica.github.io/boundedfields
initial_mod_version: 0.0.1
java_version: 17
license: MIT
mappings_name: Mojmap
modid: boundedfields
package: net.boundedfields
sources_url: https://github.com/Prismatica/boundedfields
