modid = "boundedfields"
book = "boundedfields:boundedfieldsbook"
default_lang = "en_us"
default_branch = "main"

resource_dirs = [  # top takes priority
    "resources",
    "{_common.src}/main/resources",
    { path="{^_common.src}/generated/resources", required=false },
    "{_fabric.src}/main/resources",
    { path="{^_fabric.src}/generated/resources", required=false },
    "{_forge.src}/main/resources",
    { path="{^_forge.src}/generated/resources", required=false },
    { modid="hexcasting" },
    { modid="minecraft" },
    { modid="hexdoc" },
]
export_dir = "src/hexdoc_boundedfields/_export/generated"

[template]
icon = "icon.png"
include = [
    "boundedfields",
    "hexcasting",
    "hexdoc",
]

[template.args]
mod_name = "Bounded Fields"
author = "Prismatica"
show_landing_text = false

[extra.hexcasting]
# regexes for parsing pattern registry files - try running copier update and picking a different regex if your patterns aren't loading
# NOTE: "!Raw" means "don't apply variable interpolation to this value"
_pattern_regex = { "!Raw"='make\(\s*"(?P<name>[a-zA-Z0-9_\/]+)",\s*(?:new )?(?:ActionRegistryEntry|OperationAction)\(\s*HexPattern\.fromAngles\(\s*"(?P<signature>[aqweds]+)",\s*HexDir.(?P<startdir>\w+)\)' }
_per_world_value = "true"

[[extra.hexcasting.pattern_stubs]]
path = "{^^^_common.package}/registry/BoundedFieldsPatternRegistry.java"
regex = "{^_pattern_regex}"
per_world_value = "{^_per_world_value}"

# platforms

[_common]
src = "../common/src"
package = "{src}/main/java/net/boundedfields"

[_fabric]
src = "../fabric/src"
package = "{src}/main/java/net/boundedfields/fabric"

[_forge]
src = "../forge/src"
package = "{src}/main/java/net/boundedfields/forge"
